export const ENGINE2_CONTRADICTION_MATRIX_SOURCE = 'docs/Contradiction_Matrix.pdf'

export const ENGINE2_CONTRADICTION_MATRIX_PARAMETERS = Object.freeze([
  'Weight of moving object',
  'Weight of stationary object',
  'Length of moving object',
  'Length of stationary object',
  'Area of moving object',
  'Area of stationary object',
  'Volume of moving object',
  'Volume of stationary object',
  'Speed',
  'Force',
  'Stress or pressure',
  'Shape',
  'Stability of the object',
  'Strength',
  'Duration of action by moving object',
  'Duration of action by stationary object',
  'Temperature',
  'Illumination intensity',
  'Use of energy by moving object',
  'Use of energy by stationary object',
  'Power',
  'Loss of energy',
  'Loss of substance',
  'Loss of information',
  'Loss of time',
  'Quantity of substance',
  'Reliability',
  'Measurement accuracy',
  'Manufacturing precision',
  'Object affected harmful factors',
  'Object-generated harmful factors',
  'Ease of manufacture',
  'Ease of operation',
  'Ease of repair',
  'Adaptability or versatility',
  'Device complexity',
  'Difficulty of detecting and measuring',
  'Extent of automation',
  'Productivity',
])

export const buildEngine2ContradictionMatrixReference = () => ({
  source: ENGINE2_CONTRADICTION_MATRIX_SOURCE,
  usage: 'inspiration_only',
  rule: 'Use these parameters only as internal axes for discovering potential improving/worsening requirement pairs in the confirmed context. They are not a checklist and not canned questions.',
  leakageGuard: 'Do not expose TRIZ, Contradiction Matrix, matrix parameter names, principle numbers, or matrix terminology in user-facing text unless the user used those terms first.',
  explorationPattern: [
    'start from confirmed requirements and concrete context',
    'map each requirement to possible improving axes and possible worsening axes',
    'keep only axes grounded in the whole conversation',
    'form a contradiction hypothesis with two concrete sides',
    'ask one natural question that checks both sides or a critical missing fact needed to test them',
  ],
  parameters: ENGINE2_CONTRADICTION_MATRIX_PARAMETERS,
})
